### ISSUE TITLE
NeuroML2 is LEMS

### ISSUE THREAD

**Issue by borismarin** [tarelli/org.lemsml.model#28]
org.lemsml.model can and should be used with NeuroML2 models. In order to do that, we have to explicitly state (in the schema) that NeuroML2 ComponentTypes extend the LEMS ComponentType type. If you see what I mean.
Probably relevant:

- http://confluence.highsource.org/display/MJIIP/User+Guide#UserGuide-Usingcatalogs

- http://stackoverflow.com/questions/10982740/resolving-type-definitions-from-imported-schema-in-xjc-fails

**Comment by tarelli** [comment]
+10

**Comment by borismarin** [comment]
Started experimenting with [jaxb extension / inheritance plugin](http://confluence.highsource.org/display/J2B/Inheritance+plugin) and importing the whole LEMS schema into the NML one. Will schedule meeting with @tarelli, @adrianq and @pgleeson to discuss approaches.

**Comment by borismarin** [comment]
Some experiments can be found [here](https://github.com/borismarin/org.neuroml2.model)

**Comment by borismarin** [comment]
After meeting with @pgleeson, @tarelli and @adrianq, decided to go with approach outlined on [org.neuroml2.model](https://github.com/borismarin/org.neuroml2.model). Syncing NeuroML api calls (`anIzhiCell.getA()` with `anIzhicell.getComponentType().getParameters()` will be achieved by customizing the getters/setters generated by jaxb with a plugin).

**Comment by borismarin** [comment]
Will open individual cards for tasks.
