### ISSUE TITLE
Add super class (Node?) with error field extended by all the generated model classes

### ISSUE THREAD

**Issue by tarelli** [tarelli/org.lemsml.model#30]
The super class should contain a "error" field that can be decorated by a visitor whenever a class has an error.
For instance, a component might be of a component type that doesn't exist; when we perform semantic analysis we should decorate this error field with something like "Undefined type". An enumeration is usually good to list all the possible errors. The error class should contain at the very least the line number and the error type. The _error field should be of type List<Error> as multiple errors could exist in a file.
A visitor to collect all the errors in a given Lems document should also be written so that a collection of all the errors present can be made available to whoever is invoking the compiler, e.g. an IDE.

**Comment by borismarin** [comment]
Use could use this. https://jaxb.java.net/nonav/2.0.2/docs/vendorCustomizations.html#superclass
