### ISSUE TITLE
Double inclusion

### ISSUE THREAD

**Issue by borismarin** [tarelli/org.lemsml.model#33]
As a nice side-effect of the new error checking capabilities of the compiler, we started getting "definition overwriting" warnings for all NeuroML2 examples. 

This is happening due to the fact that both (standard NeuroML2 definition files) Synapses.xml and Cells.xml  `<Include file="NeuroMLCoreCompTypes.xml">`. We should thus optimize the Include resolver to avoid double inclusion.

**Comment by tarelli** [comment]
+1

**Comment by borismarin** [comment]
@tarelli, done.  I've used hashes instead of paths, so it will catch dupes even if they are sitting in different places.
